ALTER DATABASE [AxDB] MODIFY NAME = [AxDB_original] 

ALTER DATABASE [AxDB_New] SET SINGLE_USER WITH ROLLBACK IMMEDIATE   

ALTER DATABASE [AxDB_New] MODIFY NAME = [AxDB]  

ALTER DATABASE [AxDB] SET MULTI_USER